---
apiVersion: apps/v1
kind: Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkstate-edge-v4
  template:
    metadata:
      labels:
        app: linkstate-edge-v4
    spec:
      containers:
        - args:
            - --v
            - "5"
            - --message-server
            - "broker.jalapeno:9092"
            - --database-server
            - "http://arangodb:8529"
            - --database-name
            - "jalapeno"
          image: docker.io/iejalapeno/linkstate-edge-v4:latest
          imagePullPolicy: Always
          name: linkstate-edge-v4
          volumeMounts:
            - name: credentials
              mountPath: /credentials
      volumes:
        - name: credentials
          secret:
            secretName: jalapeno
metadata:
  name: linkstate-edge-v4
  namespace: jalapeno
