apiVersion: jalapeno.srv6/v1
kind: PathRequest
metadata:
  name: amsterdam-routes
spec:
  platform: vpp
  defaultVrf:  # or defaultTable
    ipv4:
      routes:
        - name: amsterdam-to-rome-v4
          graph: ipv4_graph
          pathType: shortest_path
          metric: latency
          source: hosts/amsterdam
          destination: hosts/rome
          destination_prefix: "10.107.1.0/24"
          bsid: "101::101"  # Required for VPP
    ipv6:
      routes:
        - name: amsterdam-to-rome-v6
          graph: ipv6_graph
          pathType: shortest_path
          metric: latency
          source: hosts/amsterdam
          destination: hosts/rome
          destination_prefix: "fc00:0:107:1::/64"
          bsid: "101::102"  # Required for VPP, using different BSID for IPv6