apiVersion: jalapeno.srv6/v1
kind: PathRequest
metadata:
  name: berlin-routes
spec:
  platform: linux
  defaultVrf:
    ipv6:
      routes:

        - name: berlin-to-xrd07
          graph: ipv6_graph
          pathType: shortest_path
          metric: data-sovereignty
          excluded_countries: 
            - FRA
          direction: outbound
          source: hosts/berlin-k8s
          destination: hosts/rome
          destination_prefix: "fc00:0:7777::/48"
          outbound_interface: "ens192"