---
apiVersion: isovalent.com/v1alpha1
kind: IsovalentBGPVRFConfig
metadata:
  name: radish-config
spec:
  families:
    - afi: ipv4
      safi: mpls_vpn
      advertisements:
        matchLabels:
          advertise: "bgp-radish"

---
apiVersion: isovalent.com/v1alpha1
kind: IsovalentBGPAdvertisement
metadata:
  name: radish-adverts
  labels:
    advertise: bgp-radish
spec:
  advertisements:
    - advertisementType: "PodCIDR"

---
apiVersion: isovalent.com/v1alpha1
kind: IsovalentVRF
metadata:
  name: radish
spec:
  vrfID: 100
  locatorPoolRef: pool0
  rules:
  - selectors:
    - endpointSelector:
        matchLabels:
          vrf: radish
    destinationCIDRs:
    - 0.0.0.0/0

---
apiVersion: v1
kind: Pod
metadata:
  namespace: veggies
  labels:
    app: alpine-ping
    vrf: radish
  name: radish0
spec:
  containers:
  - image: alpine:latest
    imagePullPolicy: IfNotPresent
    name: radish0
    command:
      - /bin/sh
      - "-c"
      - "sleep 60m"

