---
apiVersion: v1
kind: Pod
metadata:
  namespace: veggies
  labels:
    app: alpine-ping
    vrf: radish
  name: carrots1
spec:
  containers:
  - image: alpine:latest
    imagePullPolicy: IfNotPresent
    name: carrots1
    command:
      - /bin/sh
      - "-c"
      - "sleep 60m"