apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata:
  name: rome
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: rome
  virtualRouters:
  - localASN: 65000
    exportPodCIDR: true
    mapSRv6VRFs: true
    srv6LocatorPoolSelector:
      matchLabels:
        export: "true"
    neighbors:
    - peerAddress: "10.0.0.5/32"
      peerASN: 65000
      families:
       - afi: ipv4
         safi: unicast
    - peerAddress: "10.0.0.6/32"
      peerASN: 65000
      families:
       - afi: ipv4
         safi: unicast
    - peerAddress: "fc00:0:5555::1/128"
      peerASN: 65000
      families:
        - afi: ipv6
          safi: unicast
        - afi: ipv4
          safi: mpls_vpn
    - peerAddress: "fc00:0:6666::1/128"
      peerASN: 65000
      families:
        - afi: ipv6
          safi: unicast
        - afi: ipv4
          safi: mpls_vpn

