---
apiVersion: apps/v1
kind: Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sr-node
  template:
    metadata:
      labels:
        app: sr-node
    spec:
      containers:
        - args:
            - --v
            - "5"
            - --message-server
            - "broker.jalapeno:9092"
            - --database-server
            - "http://arangodb.jalapeno:8529"
            - --database-name
            - "jalapeno"
          image: docker.io/iejalapeno/sr-node:latest
          imagePullPolicy: Always
          name: sr-node
          volumeMounts:
            - name: credentials
              mountPath: /credentials
      volumes:
        - name: credentials
          secret:
            secretName: jalapeno
metadata:
  name: sr-node
  namespace: jalapeno