# This is the network config written by 'subiquity'
network:
  ethernets:
    ens3:
      addresses:
        - 192.168.122.114/24
    ens4:
      addresses:
        - 10.14.1.4/24
        - 2001:db8:18:14::4/64
      nameservers:
        addresses: [8.8.8.8]
      gateway4: 10.14.1.4
      routes:
        - to: 10.0.0.0/8
          via: 10.14.1.1 
        - to: fc00:0000::/32
          via: 2001:db8:18:14::1
          on-link: true
        
  version: 2