kind: Namespace
apiVersion: v1
metadata:
  name: radish
  labels:
    name: radish

---

apiVersion: isovalent.com/v1alpha1
kind: IsovalentVRF
metadata:
  name: radish
spec:
  vrfID: 1000010
  importRouteTarget: "10:10"
  exportRouteTarget: "10:10"
  locatorPoolRef: pool0
  rules:
  - selectors:
    - endpointSelector:
        matchLabels:
          vrf: radish
    destinationCIDRs:
    - 0.0.0.0/0

---

apiVersion: v1
kind: Pod
metadata:
  namespace: radish
  labels:
    app: alpine-ping
    vrf: radish
  name: radish0
spec:
  containers:
  - image: alpine:latest
    name: redpod0
    command:
      - /bin/sh
      - "-c"
      - "sleep 60m"
