# berlin netplan

network:
  ethernets:
    ens160:
      addresses:
      - 198.18.128.104/18
      # gateway4: 198.18.128.1
      routes:
        - to: 10.0.0.0/8
          via: 198.18.128.1
    ens192:
      addresses:
      - 198.18.4.104/24
      - fc00:0:102:1::1/64
      routes:
        - to: 0.0.0.0/0
          via: 198.18.4.1
          metric: 100
        - to: fc00:0::/32
          via: fc00:0:102:1::2
      nameservers:
        addresses:
        - 198.18.128.1
        - 8.8.8.8
        search:
        - demo.dcloud.cisco.com
  version: 2

