frr defaults traditional
hostname L5
!
log stdout notifications
log commands
!
router bgp 65005
 bgp router-id 5.5.5.5
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 neighbor 2001:db8:1:5::1 remote-as 65001
 neighbor 2001:db8:1:5::1 timers 3 10
 neighbor 2001:db8:1:5::1 timers connect 1
 neighbor 2001:db8:1:5::1 capability extended-nexthop
 neighbor 2001:db8:5:9::9 remote-as 65009
 neighbor 2001:db8:5:9::9 timers 3 10
 neighbor 2001:db8:5:9::9 timers connect 1
 neighbor 2001:db8:5:9::9 capability extended-nexthop
 neighbor 2001:db8:5:10::10 remote-as 65010
 neighbor 2001:db8:5:10::10 timers 3 10
 neighbor 2001:db8:5:10::10 timers connect 1
 neighbor 2001:db8:5:10::10 capability extended-nexthop
 !
 address-family ipv6 unicast
  neighbor 2001:db8:1:5::1 activate
  neighbor 2001:db8:5:9::9 activate
  neighbor 2001:db8:5:10::10 activate
 exit-address-family
 !
 address-family ipv4 vpn
  neighbor 2001:db8:1:5::1 activate
  neighbor 2001:db8:5:9::9 activate
  neighbor 2001:db8:5:10::10 activate
 exit-address-family
 !
 address-family ipv6 vpn
  neighbor 2001:db8:1:5::1 activate
  neighbor 2001:db8:5:9::9 activate
  neighbor 2001:db8:5:10::10 activate
 exit-address-family
 !
!
interface L5-H1
 ipv6 address 2001:db8:1:5::5/64
!
interface L5-S9
 ipv6 address 2001:db8:5:9::5/64
!
interface L5-S10
 ipv6 address 2001:db8:5:10::5/64
!
ip forwarding
ipv6 forwarding
!
line vty
!