apiVersion: isovalent.com/v1alpha1
kind: IsovalentBGPClusterConfig
metadata:
  name: cilium-bgp
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: rome
  bgpInstances:
  - name: "clab-65000"
    routerID: "10.107.1.1"
    localASN: 65000
    peers:
    - name: "xrd05-rr"
      peerASN: 65000
      peerAddress: fc00:0:5555::1
      peerConfigRef:
        name: "cilium-peer"
    - name: "xrd06-rr"
      peerASN: 65000
      peerAddress: fc00:0:6666::1
      peerConfigRef:
        name: "cilium-peer"
    vrfs:
    - vrfRef: "carrots"
      rd: "9:9"
      importRTs:
        - "9:9"
      exportRTs:
        - "9:9"
      configRef: carrots-config
    - vrfRef: "radish"
      rd: "10:10"
      importRTs:
        - "10:10"
      exportRTs:
        - "10:10"
      configRef: radish-config
